### ISSUE TITLE
Binutils from 2023.09 release fail to build with disabled plugins and LTO

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#589]
```bash
git clone --branch arc-2023.09 git@github.com:foss-for-synopsys-dwc-arc-processors/binutils-gdb.git
cd binutils-gdb
mkdir build
cd build
../configure --disable-lto --disable-plugins --disable-sim --disable-gdb
make

...

  CC       ldfile.o
../../ld/ldfile.c: In function ‘ldfile_try_open_bfd’:
../../ld/ldfile.c:356:20: error: ‘struct lang_input_statement_flags’ has no member named ‘lto_output’
  356 |   if (!entry->flags.lto_output)
      |                    ^
```

Works fine on the vanilla 2.41 sources.
Reported by @wbx-github

**Comment by luismgsilva** [comment]
Issue fixed with upstream commit.
https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/121bb365ccd1d22d579eeab629ad5fbc2b31b8bd
